project:
  type: website
  output-dir: docs

website:
  title: "Math437_github"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    backgroundcolor: "#778899"
    fontcolor: "white"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



